<a href="https://colab.research.google.com/github/chinmayeeet/AIWR_assignments/blob/main/AIWR12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AIWR WEEK 1&2

The Financial Tweets dataset is used here. Appropriate and necessary libraries are imported.

In [ ]:
import nltk
import pandas as pd


df = pd.read_csv('stockerbot-export1.csv')

df.head()

            id  ... verified
0   1.0197E+18  ...     TRUE
1  1.01971E+18  ...     TRUE
2  1.01971E+18  ...     TRUE
3  1.01972E+18  ...     TRUE
4  1.01972E+18  ...     TRUE

[5 rows x 8 columns]

**CLEANING THE TWEETS BY PURGING URLS, HYPERLINKS, SPECIAL CHARACTERS AND EXTRA WHITESPACES.**

In [ ]:
pat1 = r'@[A-Za-z0-9]+' # this is to remove any text with @....
pat2 = r'https?://[A-Za-z0-9./]+'  # this is to remove the urls
combined_pat = r'|'.join((pat1, pat2)) 
pat3 = r'[^a-zA-Z]' # to remove every other character except a-z & A-Z
combined_pat2 = r'|'.join((combined_pat,pat3))

In [ ]:
import re
import nltk

pat1 = r'@[A-Za-z0-9]+' # this is to remove any text with @....
pat2 = r'https?://[A-Za-z0-9./]+'  # this is to remove the urls
combined_pat = r'|'.join((pat1, pat2)) 
pat3 = r'[^a-zA-Z]' # to remove every other character except a-z & A-Z
combined_pat2 = r'|'.join((combined_pat,pat3))

dtweets = []

for i in range(0, len(df['text'])) : 
    w = df['text'][i]
    w.strip()
    tweets = re.sub(combined_pat2,' ',w)
    wtweets = re.sub(' +',' ',tweets)
    dtweets.append(wtweets)
df['Tweets'] = dtweets   
df['Tweets'].head()

0    VIDEO I was in my office I was minding my own ...
1    The price of lumber LB F is down since hitting...
2                 Who says the American Dream is dead
3    Barry Silbert is extremely optimistic on bitco...
4    How satellites avoid attacks and space junk wh...
Name: Tweets, dtype: object

**STEP 1 CASE FOLDING**

We lower the case of all the tweets using .lower().

In [ ]:
import string
string.punctuation
def remove_punctuation(text):
    punctuationfree="".join([i for i in text if i not in string.punctuation])
    return punctuationfree

df['Tweets']= df['Tweets'].apply(lambda x:remove_punctuation(x))
df['Tweets']= df['Tweets'].apply(lambda x: x.lower())
df['Tweets'].head()

0    video i was in my office i was minding my own ...
1    the price of lumber lb f is down since hitting...
2                 who says the american dream is dead
3    barry silbert is extremely optimistic on bitco...
4    how satellites avoid attacks and space junk wh...
Name: Tweets, dtype: object

**STEP 2 TOKENIZE**

We tokenize the tweets and identify the tokens by using the regex library.

In [ ]:
import re
def tokenization(text):
    tokens = re.split('\W',text)
    return tokens
#applying function to the column
df['Tweet_token']= df['Tweets'].apply(lambda x: tokenization(x))
df[df.columns[8:]].head()

                                              Tweets                                        Tweet_token
0  video i was in my office i was minding my own ...  [video, i, was, in, my, office, i, was, mindin...
1  the price of lumber lb f is down since hitting...  [the, price, of, lumber, lb, f, is, down, sinc...
2               who says the american dream is dead       [who, says, the, american, dream, is, dead, ]
3  barry silbert is extremely optimistic on bitco...  [barry, silbert, is, extremely, optimistic, on...
4  how satellites avoid attacks and space junk wh...  [how, satellites, avoid, attacks, and, space, ...

**STEP 3 STOPWORDS REMOVAL**

We remove the stopwords by using the the stopwords library to filter out the tweets.

In [ ]:
import nltk
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output
df['Tweet_stopw']= df['Tweet_token'].apply(lambda x:remove_stopwords(x))
df[df.columns[8:]].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

                                              Tweets  ...                                        Tweet_stopw
0  video i was in my office i was minding my own ...  ...  [video, office, minding, business, david, solo...
1  the price of lumber lb f is down since hitting...  ...  [price, lumber, lb, f, since, hitting, ytd, hi...
2               who says the american dream is dead   ...                    [says, american, dream, dead, ]
3  barry silbert is extremely optimistic on bitco...  ...  [barry, silbert, extremely, optimistic, bitcoi...
4  how satellites avoid attacks and space junk wh...  ...  [satellites, avoid, attacks, space, junk, circ...

[5 rows x 3 columns]

**STEP 4 STEMMING**

Stemming is done on the tweets using PorterStemmer from the NLTK Library

In [ ]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
def stemming(text):
    stweets= [ps.stem(word) for word in text]
    return stweets
df['Tweet_stem']=df['Tweet_stopw'].apply(lambda x: stemming(x))
df[df.columns[8:]].head()

                                              Tweets  ...                                         Tweet_stem
0  video i was in my office i was minding my own ...  ...  [video, offic, mind, busi, david, solomon, tel...
1  the price of lumber lb f is down since hitting...  ...  [price, lumber, lb, f, sinc, hit, ytd, high, m...
2               who says the american dream is dead   ...                     [say, american, dream, dead, ]
3  barry silbert is extremely optimistic on bitco...  ...  [barri, silbert, extrem, optimist, bitcoin, pr...
4  how satellites avoid attacks and space junk wh...  ...  [satellit, avoid, attack, space, junk, circl, ...

[5 rows x 4 columns]

**STEP  5 LEMMATIZATION**

Lemmatization is perform using the inbuilt library WordNetLemmatizer.

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
def lemm(text):
    ltweets = [lemmatizer.lemmatize(word) for word in text]
    return ltweets
df['Tweet_lem']=df['Tweet_stopw'].apply(lambda x:lemm(x))
df[df.columns[8:]].head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

                                              Tweets  ...                                          Tweet_lem
0  video i was in my office i was minding my own ...  ...  [video, office, minding, business, david, solo...
1  the price of lumber lb f is down since hitting...  ...  [price, lumber, lb, f, since, hitting, ytd, hi...
2               who says the american dream is dead   ...                     [say, american, dream, dead, ]
3  barry silbert is extremely optimistic on bitco...  ...  [barry, silbert, extremely, optimistic, bitcoi...
4  how satellites avoid attacks and space junk wh...  ...  [satellite, avoid, attack, space, junk, circli...

[5 rows x 5 columns]

**STEP 6  INVERTED INDEX**

Finally we create an inverted index that maps the words to its location in the document.

In [ ]:
dict = {}
  
for i in range(0,len(df['Tweet_stopw'])):
    check = df['Tweets'][i].lower()
    for item in df['Tweet_stopw'][i]:
  
        if item in check:
            if item not in dict:
                dict[item] = []
  
            if item in dict:
                dict[item].append(i+1)
dict['video']
dict['office']

[1,
 340,
 343,
 653,
 838,
 839,
 1261,
 1266,
 1923,
 1924,
 1979,
 2035,
 2038,
 2990,
 3229,
 3360,
 3526,
 3838,
 3977,
 4570,
 4686,
 5199,
 5314,
 5633,
 6641,
 6646,
 6762,
 6775,
 6779,
 7183,
 7251,
 7294,
 7391,
 8693,
 8694,
 12251,
 12280,
 12286,
 14823,
 15109,
 15129,
 15839,
 16611,
 19983,
 20934,
 20946,
 27525,
 27528]

In [ ]:
cleaned_tweets = df['Tweet_stem']
cleaned_tweets

0        [video, offic, mind, busi, david, solomon, tel...
1        [price, lumber, lb, f, sinc, hit, ytd, high, m...
2                           [say, american, dream, dead, ]
3        [barri, silbert, extrem, optimist, bitcoin, pr...
4        [satellit, avoid, attack, space, junk, circl, ...
                               ...
28435                           [, fb, c, f, f, cb, ecf, ]
28436                                            [, btc, ]
28437    [rt, hd, nuff, said, tel, telcoin, telfam, cry...
28438                                            [, btc, ]
28439    [stellar, xlm, price, binanc, registr, open, l...
Name: Tweet_stem, Length: 28440, dtype: object